# Generated by Django 3.0.6 on 2020-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typesBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestsbox',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='typesbox',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
