# Generated by Django 3.0.6 on 2020-05-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typesBox', '0002_auto_20200522_0553'),
        ('accounts', '0003_auto_20200522_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='interests',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='interests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typesBox.InterestsBox'),
        ),
    ]
